var songBank = [
    {
        name: "Jurrasic Park Theme",
        ref: 60,
        bpm: 120,
        parts: [
           {
                partType:'Melody',
                notes:[
                    {pitch: 12, duration: .5, timing: 0},
                    {pitch: 11, duration: .5, timing: .5},
                    {pitch: 12, duration: 1, timing: 1},
                    {pitch: 7, duration: 1, timing: 2},
                    {pitch: 5, duration: 1, timing: 3},
                    {pitch: 12, duration: .5, timing: 4},
                    {pitch: 11, duration: .5, timing: 4.5},
                    {pitch: 12, duration: 1, timing: 5},
                    {pitch: 7, duration: 1, timing: 6},
                    {pitch: 5, duration: 1, timing: 7},
                    {pitch: 12, duration: .5, timing: 8},
                    {pitch: 11, duration: .5, timing: 8.5},
                    {pitch: 12, duration: 1, timing: 9},
                    {pitch: 7, duration: 1.5, timing: 10.5},
                    {pitch: 0, duration: .5, timing: 11},
                    {pitch: 9, duration: 2, timing: 11.5},
                ]
            }
        ]
    },
    {
        name:'My Funny Valentine',
        ref: 60,
        bpm: 120,
        parts: [
            {
                partType: 'Bass',
                notes: [
                    //
                    {pitch:0,duration:4,timing:0},
                    {pitch:-1,duration:4,timing:4},
                    {pitch:-2,duration:4,timing:8},
                    {pitch:-3,duration:4,timing:12},
                    {pitch:-4,duration:4,timing:16},
                    {pitch:-7,duration:4,timing:20},
                    {pitch:-10,duration:4,timing:24},
                    {pitch:-5,duration:4,timing:28},
                    //
                    {pitch:0,duration:4,timing:32},
                    {pitch:-1,duration:4,timing:36},
                    {pitch:-2,duration:4,timing:40},
                    {pitch:-3,duration:4,timing:44},
                    {pitch:-4,duration:4,timing:48},
                    {pitch:-7,duration:4,timing:52},
                    {pitch:-7,duration:4,timing:56},
                    {pitch:-2,duration:4,timing:60},
                    //
                    {pitch:3,duration:2,timing:64},
                    {pitch:5,duration:2,timing:66},
                    {pitch:7,duration:2,timing:68},
                    {pitch:5,duration:2,timing:70},
                    {pitch:3,duration:2,timing:72},
                    {pitch:5,duration:2,timing:74},
                    {pitch:7,duration:2,timing:76},
                    {pitch:5,duration:2,timing:78},
                    //
                    {pitch:3,duration:2,timing:80},
                    {pitch:7,duration:2,timing:82},
                    {pitch:0,duration:2,timing:84},
                    {pitch:-2,duration:1,timing:86},
                    {pitch:-3,duration:1,timing:87},
                    {pitch:-4,duration:4,timing:88},
                    {pitch:2,duration:2,timing:92},
                    {pitch:-5,duration:2,timing:94},
                    //
                    {pitch:0,duration:4,timing:96},
                    {pitch:-1,duration:4,timing:100},
                    {pitch:-2,duration:4,timing:104},
                    {pitch:-3,duration:4,timing:108},
                    {pitch:-4,duration:4,timing:112},
                    {pitch:2,duration:2,timing:116},
                    {pitch:-5,duration:2,timing:118},
                    {pitch:0,duration:4,timing:120},
                    {pitch:-2,duration:2,timing:124},
                    {pitch:-3,duration:2,timing:126},
                    {pitch:-4,duration:4,timing:128},
                    {pitch:-7,duration:2,timing:132},
                    {pitch:-2,duration:2,timing:134},
                    {pitch:-9,duration:4,timing:136},
                ]
            },
            {
                partType: "Melody",
                notes: [
                    {pitch:0,duration:2,timing:0},
                    {pitch:2,duration:1,timing:2},
                    {pitch:3,duration:1,timing:3},
                    {pitch:2,duration:1.5,timing:4},
                    {pitch:3,duration:.5,timing:5.5},
                    {pitch:2,duration:2,timing:6},
                    {pitch:0,duration:2,timing:8},
                    {pitch:2,duration:1,timing:10},
                    {pitch:3,duration:1,timing:11},
                    {pitch:2,duration:1.5,timing:12},
                    {pitch:3,duration:.5,timing:13.5},
                    {pitch:2,duration:2,timing:14},
                    {pitch:0,duration:2,timing:16},
                    {pitch:2,duration:1,timing:18},
                    {pitch:3,duration:1,timing:19},
                    {pitch:10,duration:2,timing:20},
                    {pitch:8,duration:1,timing:22},
                    {pitch:7,duration:1,timing:23},
                    {pitch:5,duration:8,timing:24},
                    //
                    {pitch:3,duration:2,timing:32},
                    {pitch:5,duration:1,timing:34},
                    {pitch:7,duration:1,timing:35},
                    {pitch:5,duration:1.5,timing:36},
                    {pitch:7,duration:.5,timing:37.5},
                    {pitch:5,duration:2,timing:38},
                    {pitch:3,duration:2,timing:40},
                    {pitch:5,duration:1,timing:42},
                    {pitch:7,duration:1,timing:43},
                    {pitch:5,duration:1.5,timing:44},
                    {pitch:7,duration:.5,timing:45.5},
                    {pitch:5,duration:2,timing:46},
                    {pitch:3,duration:2,timing:48},
                    {pitch:5,duration:1,timing:50},
                    {pitch:7,duration:1,timing:51},
                    {pitch:14,duration:1.5,timing:52},
                    {pitch:12,duration:.5,timing:53.5},
                    {pitch:10,duration:1.5,timing:54},
                    {pitch:9,duration:.5,timing:55.5},
                    {pitch:8,duration:6,timing:56},
                    {pitch:7,duration:1,timing:62},
                    {pitch:5,duration:1,timing:63},
                    //
                    {pitch:10,duration:1.5,timing:64},
                    {pitch:3,duration:.5,timing:65.5},
                    {pitch:3,duration:1,timing:66},
                    {pitch:2,duration:1,timing:67},
                    {pitch:3,duration:2,timing:68},
                    {pitch:3,duration:1,timing:70},
                    {pitch:2,duration:1,timing:71},
                    {pitch:12,duration:1.5,timing:72},
                    {pitch:3,duration:.5,timing:73.5},
                    {pitch:3,duration:1,timing:74},
                    {pitch:2,duration:1,timing:75},
                    {pitch:3,duration:2,timing:76},
                    {pitch:3,duration:1,timing:78},
                    {pitch:2,duration:1,timing:79},
                    {pitch:14,duration:1.5,timing:80},
                    {pitch:3,duration:.5,timing:81.5},
                    {pitch:3,duration:1,timing:82},
                    {pitch:2,duration:1,timing:83},
                    {pitch:3,duration:2,timing:84},
                    {pitch:5,duration:1,timing:86},
                    {pitch:7,duration:1,timing:87},
                    {pitch:12,duration:6,timing:88},
                    {pitch:3,duration:1,timing:94},
                    {pitch:2,duration:1,timing:95},
                    //
                    {pitch:0,duration:2,timing:96},
                    {pitch:2,duration:1,timing:98},
                    {pitch:3,duration:1,timing:99},
                    {pitch:2,duration:1.5,timing:100},
                    {pitch:3,duration:.5,timing:101.5},
                    {pitch:2,duration:2,timing:102},
                    {pitch:3,duration:2,timing:104},
                    {pitch:5,duration:1,timing:106},
                    {pitch:7,duration:1,timing:107},
                    {pitch:5,duration:1.5,timing:108},
                    {pitch:7,duration:.5,timing:109.5},
                    {pitch:5,duration:2,timing:110},
                    {pitch:12,duration:2,timing:112},
                    {pitch:14,duration:1,timing:114},
                    {pitch:15,duration:1,timing:115},
                    {pitch:17,duration:1.5,timing:116},
                    {pitch:15,duration:.5,timing:117.5},
                    {pitch:14,duration:2,timing:118},
                    {pitch:15,duration:8,timing:120},
                    //
                    {pitch:3,duration:2,timing:128},
                    {pitch:5,duration:1,timing:130},
                    {pitch:7,duration:1,timing:131},
                    {pitch:5,duration:1.5,timing:132},
                    {pitch:7,duration:.5,timing:133.5},
                    {pitch:5,duration:2,timing:134},
                    {pitch:3,duration:4,timing:136}
                ]
            }
        ]
    }
];

module.exports = songBank 