var songBank = [
    {
        name: "Jurrasic Park Theme",
        ref: 60,
        bpm: 120,
        parts: [
           {
                partType:'Melody',
                notes:[
                    {pitch: 12, duration: .5, time: 0},
                    {pitch: 11, duration: .5, time: .5},
                    {pitch: 12, duration: 1, time: 1},
                    {pitch: 7, duration: 1, time: 2},
                    {pitch: 5, duration: 1, time: 3},
                    {pitch: 12, duration: .5, time: 4},
                    {pitch: 11, duration: .5, time: 4.5},
                    {pitch: 12, duration: 1, time: 5},
                    {pitch: 7, duration: 1, time: 6},
                    {pitch: 5, duration: 1, time: 7},
                    {pitch: 12, duration: .5, time: 8},
                    {pitch: 11, duration: .5, time: 8.5},
                    {pitch: 12, duration: 1, time: 9},
                    {pitch: 7, duration: 1.5, time: 10.5},
                    {pitch: 0, duration: .5, time: 11},
                    {pitch: 9, duration: 2, time: 11.5},
                ]
            }
        ]
    },
    {
        name:'My Funny Valentine',
        ref: 60,
        bpm: 120,
        parts: [
            {
                partType: 'Bass',
                notes: [
                    //
                    {pitch:0,duration:4,time:0},
                    {pitch:-1,duration:4,time:4},
                    {pitch:-2,duration:4,time:8},
                    {pitch:-3,duration:4,time:12},
                    {pitch:-4,duration:4,time:16},
                    {pitch:-7,duration:4,time:20},
                    {pitch:-10,duration:4,time:24},
                    {pitch:-5,duration:4,time:28},
                    //
                    {pitch:0,duration:4,time:32},
                    {pitch:-1,duration:4,time:36},
                    {pitch:-2,duration:4,time:40},
                    {pitch:-3,duration:4,time:44},
                    {pitch:-4,duration:4,time:48},
                    {pitch:-7,duration:4,time:52},
                    {pitch:-7,duration:4,time:56},
                    {pitch:-2,duration:4,time:60},
                    //
                    {pitch:3,duration:2,time:64},
                    {pitch:5,duration:2,time:66},
                    {pitch:7,duration:2,time:68},
                    {pitch:5,duration:2,time:70},
                    {pitch:3,duration:2,time:72},
                    {pitch:5,duration:2,time:74},
                    {pitch:7,duration:2,time:76},
                    {pitch:5,duration:2,time:78},
                    //
                    {pitch:3,duration:2,time:80},
                    {pitch:7,duration:2,time:82},
                    {pitch:0,duration:2,time:84},
                    {pitch:-2,duration:1,time:86},
                    {pitch:-3,duration:1,time:87},
                    {pitch:-4,duration:4,time:88},
                    {pitch:2,duration:2,time:92},
                    {pitch:-5,duration:2,time:94},
                    //
                    {pitch:0,duration:4,time:96},
                    {pitch:-1,duration:4,time:100},
                    {pitch:-2,duration:4,time:104},
                    {pitch:-3,duration:4,time:108},
                    {pitch:-4,duration:4,time:112},
                    {pitch:2,duration:2,time:116},
                    {pitch:-5,duration:2,time:118},
                    {pitch:0,duration:4,time:120},
                    {pitch:-2,duration:2,time:124},
                    {pitch:-3,duration:2,time:126},
                    {pitch:-4,duration:4,time:128},
                    {pitch:-7,duration:2,time:132},
                    {pitch:-2,duration:2,time:134},
                    {pitch:-9,duration:4,time:136},
                ]
            },
            {
                partType: "Melody",
                notes: [
                    {pitch:0,duration:2,time:0},
                    {pitch:2,duration:1,time:2},
                    {pitch:3,duration:1,time:3},
                    {pitch:2,duration:1.5,time:4},
                    {pitch:3,duration:.5,time:5.5},
                    {pitch:2,duration:2,time:6},
                    {pitch:0,duration:2,time:8},
                    {pitch:2,duration:1,time:10},
                    {pitch:3,duration:1,time:11},
                    {pitch:2,duration:1.5,time:12},
                    {pitch:3,duration:.5,time:13.5},
                    {pitch:2,duration:2,time:14},
                    {pitch:0,duration:2,time:16},
                    {pitch:2,duration:1,time:18},
                    {pitch:3,duration:1,time:19},
                    {pitch:10,duration:2,time:20},
                    {pitch:8,duration:1,time:22},
                    {pitch:7,duration:1,time:23},
                    {pitch:5,duration:8,time:24},
                    //
                    {pitch:3,duration:2,time:32},
                    {pitch:5,duration:1,time:34},
                    {pitch:7,duration:1,time:35},
                    {pitch:5,duration:1.5,time:36},
                    {pitch:7,duration:.5,time:37.5},
                    {pitch:5,duration:2,time:38},
                    {pitch:3,duration:2,time:40},
                    {pitch:5,duration:1,time:42},
                    {pitch:7,duration:1,time:43},
                    {pitch:5,duration:1.5,time:44},
                    {pitch:7,duration:.5,time:45.5},
                    {pitch:5,duration:2,time:46},
                    {pitch:3,duration:2,time:48},
                    {pitch:5,duration:1,time:50},
                    {pitch:7,duration:1,time:51},
                    {pitch:14,duration:1.5,time:52},
                    {pitch:12,duration:.5,time:53.5},
                    {pitch:10,duration:1.5,time:54},
                    {pitch:9,duration:.5,time:55.5},
                    {pitch:8,duration:6,time:56},
                    {pitch:7,duration:1,time:62},
                    {pitch:5,duration:1,time:63},
                    //
                    {pitch:10,duration:1.5,time:64},
                    {pitch:3,duration:.5,time:65.5},
                    {pitch:3,duration:1,time:66},
                    {pitch:2,duration:1,time:67},
                    {pitch:3,duration:2,time:68},
                    {pitch:3,duration:1,time:70},
                    {pitch:2,duration:1,time:71},
                    {pitch:12,duration:1.5,time:72},
                    {pitch:3,duration:.5,time:73.5},
                    {pitch:3,duration:1,time:74},
                    {pitch:2,duration:1,time:75},
                    {pitch:3,duration:2,time:76},
                    {pitch:3,duration:1,time:78},
                    {pitch:2,duration:1,time:79},
                    {pitch:14,duration:1.5,time:80},
                    {pitch:3,duration:.5,time:81.5},
                    {pitch:3,duration:1,time:82},
                    {pitch:2,duration:1,time:83},
                    {pitch:3,duration:2,time:84},
                    {pitch:5,duration:1,time:86},
                    {pitch:7,duration:1,time:87},
                    {pitch:12,duration:6,time:88},
                    {pitch:3,duration:1,time:94},
                    {pitch:2,duration:1,time:95},
                    //
                    {pitch:0,duration:2,time:96},
                    {pitch:2,duration:1,time:98},
                    {pitch:3,duration:1,time:99},
                    {pitch:2,duration:1.5,time:100},
                    {pitch:3,duration:.5,time:101.5},
                    {pitch:2,duration:2,time:102},
                    {pitch:3,duration:2,time:104},
                    {pitch:5,duration:1,time:106},
                    {pitch:7,duration:1,time:107},
                    {pitch:5,duration:1.5,time:108},
                    {pitch:7,duration:.5,time:109.5},
                    {pitch:5,duration:2,time:110},
                    {pitch:12,duration:2,time:112},
                    {pitch:14,duration:1,time:114},
                    {pitch:15,duration:1,time:115},
                    {pitch:17,duration:1.5,time:116},
                    {pitch:15,duration:.5,time:117.5},
                    {pitch:14,duration:2,time:118},
                    {pitch:15,duration:8,time:120},
                    //
                    {pitch:3,duration:2,time:128},
                    {pitch:5,duration:1,time:130},
                    {pitch:7,duration:1,time:131},
                    {pitch:5,duration:1.5,time:132},
                    {pitch:7,duration:.5,time:133.5},
                    {pitch:5,duration:2,time:134},
                    {pitch:3,duration:4,time:136}
                ]
            }
        ]
    }
];

module.exports = songBank 